[package]
name = "cwe_checker_install"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

directories = "3.0"
walkdir = "2"
fs_extra = "1.2.0"
