name: Acceptance tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always

jobs:

  acceptance-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - name: Build the cwe_checker docker image
        run: docker build -t cwe_checker .
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.82.0
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --locked --no-fail-fast -p acceptance_tests_ghidra -F docker -- --show-output --ignored


  docker-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build the docker image
        run: docker build -t cwe_checker .
      - name: Check functionality of the image
        run: docker run --rm cwe_checker /bin/echo | grep -q CWE676
