name: Publish Docker images for release versions

on:
  release:
    types: [published]

jobs:
  build-and-publish-image:
    runs-on: ubuntu-latest

    steps:
      - name: Get tag name
        uses: olegtarasov/get-tag@v2.1
        id: tagName

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build test docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          load: true
          tags: cwe_checker:test

      - name: Check functionality of the image
        run: docker run --rm cwe_checker:test /bin/echo | grep -q CWE676

        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/fkie-cad/cwe_checker:${{ steps.tagName.outputs.tag }}