name: Publish Docker image based on master branch

on:
  push:
    branches: ['master', 'update_docker_action']

jobs:
  build-and-publish-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build test docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          load: true
          tags: cwe_checker:test

      - name: Check functionality of the image
        run: docker run --rm cwe_checker:test /bin/echo | grep -q CWE676

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to ghcr.io Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: |
            linux/amd64
            # linux/arm64  # temporarily disabled due to memory exhaustion problems in the CI
          push: true
          tags: |
            fkiecad/cwe_checker:latest
            ghcr.io/fkie-cad/cwe_checker:latest